variable "secrets" {
  description = "https://app.datadoghq.com/account/settings#api"
  type        = "map"
  default = {
    api_key = ""
    app_key = ""
  }
}

variable "prefix" {
  description = "metric prefix to pattern match against available metrics in datadog also used for dashboard title"
  type        = "string"
  default     = ""
}

variable "description" {
  description = "datadog dashboard description"
  type        = "string"
  default     = "generated by Terraform"
}
