module "datadog_dashboard" {
  source      = "../"
  prefix      = "app.dev.memstats"
  api_key     = "your_datadog_api_key"
  app_key     = "your_datadog_app_key"
  description = "generated by Terraform"
}
